# ╔═══════════════════════════════════════════════════════════════════════════╗
# ║ Overmind Process Configuration                                            ║
# ╚═══════════════════════════════════════════════════════════════════════════╝

# Application services
vaultwarden: /vaultwarden
caddy: caddy run --config /Caddyfile
crontab: supercronic /crontab