name: 🧹 Clean GHCR SHA256 Images

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

permissions:
  packages: write
  contents: read

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - name: 🧾 Delete SHA256-named GHCR images
        env:
          GH_TOKEN: ${{ github.token }}
          REPO_NAME: ${{ github.repository }}
          PACKAGE_NAME: adguard
        run: |
          echo "🔍 REPO_NAME: $REPO_NAME"
          echo "🔍 PACKAGE_NAME: $PACKAGE_NAME"

          echo "🔍 Fetching all package versions for $PACKAGE_NAME..."
          VERSIONS_JSON=$(gh api -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GH_TOKEN" \
            /user/packages/container/$PACKAGE_NAME/versions \
            --paginate)

          if [ -z "$VERSIONS_JSON" ]; then
            echo "❌ No versions found or API request failed."
            exit 1
          fi

          echo "📜 Raw versions JSON:"
          echo "$VERSIONS_JSON" | jq .

          VERSIONS=$(echo "$VERSIONS_JSON" | jq -r 'sort_by(.created_at) | reverse | .[] | select(.name | startswith("sha256:")) | .id')

          if [ -z "$VERSIONS" ]; then
            echo "✅ No SHA256-named versions found."
            exit 0
          fi

          echo "📋 Found SHA256-named version IDs:"
          echo "$VERSIONS" | while read -r vid; do echo "  - $vid"; done

          for vid in $VERSIONS; do
            echo "🗑️ Attempting to delete version ID: $vid"
            if ! gh api -X DELETE \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer $GH_TOKEN" \
              /user/packages/container/$PACKAGE_NAME/versions/$vid 2> error.log; then
              if grep -q "You cannot delete the last tagged version" error.log; then
                echo "⚠️ Skipped version ID: $vid (last tagged version)"
              else
                echo "❌ Failed to delete version ID: $vid (unexpected error)"
                cat error.log
              fi
            else
              echo "✅ Successfully deleted version ID: $vid"
            fi
          done
